[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
   let g:lightline = {
   \ 'colorscheme': 'wombat',
   \ 'component': {
   \   'readonly': '%{&readonly?"x":""}',
   \ },
   \ 'separator': { 'left': "\u2b80", 'right': "\u2b82" },
   \ 'subseparator': { 'left': "\u2b81", 'right': "\u2b83" }
   \ }
'''

[[plugins]] #TomL
repo = 'cespare/vim-toml'
on_ft = 'toml'
